### ISSUE TITLE
Suggestion: Create Attribute Filter compatibility

### ISSUE THREAD

**Issue by HarbingerOfCrazy** [SiverDX/quality_food#1]
Add compatibility for Create(mod) Attribute filters for each Quality.

**Comment by SiverDX** [comment]
If Create does not support filtering NBT data then that's that

There is also no thread-safe way of adding custom ones
https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/main/java/com/simibubi/create/content/logistics/filter/ItemAttribute.java
