### ISSUE TITLE
Default Crop Quality is set to 5 instead of 0, allowing easy seed quality rerolls in Survival

### ISSUE THREAD

**Issue by goldrat1** [SiverDX/quality_food#15]
I've noticed that if I get some seeds, whether from the creative inventory or from loot tables, if I get normal (none-quality) seeds, whenever I place them onto Farmland, there's an NBT tag listed whenever I hover over the block in F3 mode:
`quality_food: 5`
This leads me to believe that by default a crop's quality value is set to 5 rather than what it realistically should be which is 0. I didn't think this was really a problem, until I realised that _breaking_ a crop can change it's Quality to something other than 5 (because 5 isn't an actual quality value AFAIK). 
So if you have normal non-quality seeds, you can just keep placing and breaking them until you get Iron, Gold or Diamond seeds, and once you have them, placing and breaking them keeps their quality, so it can only go up.

I think that if by default crops/seeds had a quality value of 0 this would prevent this, but I don't know how the mod's code works so I could be mistaken.
Hope this is fixed soon because it lets people get high-quality seeds by doing basically nothing would be pretty gamebreaking in the farming-based modpack that I'm making.

Really loving the mod, can't wait to work with it more in the future!

**Comment by SiverDX** [comment]
5 is the value for player placed crops which has no quality (to differentiate between natural no quality whose drops can roll quality)

There is a check for non-fully-grown crops which prevents quality from being rolled when it's player placed
Meaning breaking player placed crops should only roll quality if it's fully grown which sounds correct to me 

https://github.com/SiverDX/quality_food/blob/7b35387a700d65f81f8ecb428dffcf0b1688a0d5/src/main/java/de/cadentem/quality_food/util/QualityUtils.java#L160-L181

**Comment by goldrat1** [comment]
That might be the intended design and that makes sense to me, but on a fresh install of Forge with only Quality Food installed (no other loot tables or datapacks), Wheat Seeds that you get from Grass can be placed down and instantly broken to reroll their quality, no need to grow them to full. Is the grown-crop check working?
