### ISSUE TITLE
Decompacting compacted food items that don't have quality tag has a chance of getting higher value items as an output

### ISSUE THREAD

**Issue by goldrat1** [SiverDX/quality_food#19]
When taking a crop (say, nine Sweet Berries of n/a quality) and crafting it into a compact block (say, Quark's Berry Sack), un-crafting that item can give nine of any given quality of crops.
This happens with any compacting recipe, including vanilla ones (like Hay Bales), and it lets you turn items into blocks into higher value items with ease and totally breaks progression in this mod and others.

There's something on the mod page that mentions something about compacting recipes:
_"(De)compacting recipes are handled separately from this tag"_
...but there isn't any indication how to fix it with datapacks or whatever this is referring to.
Is this a bug or is there something I need to do with every compacting recipe to fix this?

**Comment by SiverDX** [comment]
you can test with this version:
[quality_food-1.20.1-1.6.0-all.zip](https://github.com/user-attachments/files/16016110/quality_food-1.20.1-1.6.0-all.zip)

added a recipe blacklist config with some default entries 
(no quality will be applied to the result items for these) 
(conversion will still be done though, aka quality will be retained)

**Comment by SiverDX** [comment]
Released with 1.6.0
