### ISSUE TITLE
[1.20.1] - Crash on Launch

### ISSUE THREAD

**Issue by ToxinZangoose** [SiverDX/quality_food#20]
Hello,

I found a bug with Quality Foods, when launching the game, it crashes due to a mixin error.

Here is the latest log.
[latest.log](https://github.com/user-attachments/files/16023201/latest.log)

**Comment by SiverDX** [comment]
see https://github.com/SiverDX/quality_food/issues/2

**Comment by ToxinZangoose** [comment]
Thank you!
