### ISSUE TITLE
[Support] Harvest with Ease

### ISSUE THREAD

**Issue by SaltSouls** [SiverDX/quality_food#21]
I know that you already have quart auto replant support, but it would be nice if we could also get support for harvest with ease. That is unless it is already supported and I'm just unaware.

**Comment by SiverDX** [comment]
did you notice any issues? it should already be supported

**Comment by SaltSouls** [comment]
Haven't tried a whole lot of crops just yet, but I have noticed that at least with the FD tomatoes, that I don't seem to be getting any higher quality crops. Maybe I'm just unlucky, or maybe it has to do with me using the supplementaries stick block as their support. Regardless I will report further if I notice this happening with other crops as well.

**Comment by SiverDX** [comment]
No response
