### ISSUE TITLE
[Suggestion] Create Mechanical Harvester and Bulk Smoking Compat

### ISSUE THREAD

**Issue by geesl** [SiverDX/quality_food#23]
Would it also be possible to have compatability with both of those machines to fully automate the harvesting process? Or does Create do some funky stuff, making it impossible?

**Comment by SiverDX** [comment]
Added compatibility so quality gets applied when cooking with a fan (was that what you meant?) and through harvesting
Also added sth. so harvesting should retain quality when things get re-planted

Don't know much about create, so I only was able to test the fan one
[quality_food-1.20.1-1.7.3-all.zip](https://github.com/user-attachments/files/16772743/quality_food-1.20.1-1.7.3-all.zip)

**Comment by SiverDX** [comment]
Version that does not crash the game:
[quality_food-1.20.1-1.7.3-all.zip](https://github.com/user-attachments/files/16773234/quality_food-1.20.1-1.7.3-all.zip)

**Comment by geesl** [comment]
Yes, that is exactly it. Thank you this is amazing!
