### ISSUE TITLE
Mixin Init Crash

### ISSUE THREAD

**Issue by desagas** [SiverDX/quality_food#25]
Both 1.21.1 versions will not load with the mods I have installed. It is only Quality Food, no other mod. Without it, everything loads perfectly fine, and with in, it does not even load the loading screens.

So, 1.21.1.2.1.1 for your mod, and .37 for Neoforge.

My crash log: 
[crash-2024-09-05_10.18.15-client.txt](https://github.com/user-attachments/files/16897540/crash-2024-09-05_10.18.15-client.txt)

My log:
[latest.log](https://github.com/user-attachments/files/16897542/latest.log)

My debug log: 
[debug.log](https://github.com/user-attachments/files/16897548/debug.log)

**Comment by SiverDX** [comment]
it's because of https://www.curseforge.com/minecraft/mc-mods/fuelgoeshere
they have a very incompatible mixin regarding the furnace
