### ISSUE TITLE
Crashing on 1.20.1

### ISSUE THREAD

**Issue by FemBane** [SiverDX/quality_food#29]
Crashlog: https://mclo.gs/dNH86Ol
Not exactly sure when this started happening, it's exclusively when you open the creative menu.
May be a mod conflict, I'll figure out which one in particular tomorrow

**Comment by SiverDX** [comment]
added a check, not sure why there would be items with food property which explicitly state they have effects but then provide no effect in their effects entry

**Comment by FemBane** [comment]
Huh, I'll have to figure out what item has that condition.
I could definitely see it happening if it's provided in some sort of builder that would presume an effect is provided, but they later added one or two that used the builder but excluded an actual effect
