### ISSUE TITLE
Fuel Goes Here Incompatibility

### ISSUE THREAD

**Issue by Wise2D** [SiverDX/quality_food#33]
Hi, just want to notify and incompatibility, with "Fuel Goes Here" mod, ignore 900+ mod list just an experimental mod pack :P

[2024-11-02-7.log](https://github.com/user-attachments/files/17608878/2024-11-02-7.log)

![Captura de tela 2024-11-02 222434](https://github.com/user-attachments/assets/b63b5b4c-b627-40cd-b926-fce78a70706c)

**Comment by SiverDX** [comment]
See https://github.com/SiverDX/quality_food/issues/25

Their code is not suitable for compatibility

**Comment by Wise2D** [comment]
Omg, that was fast as hell.
