### ISSUE TITLE
Furnaces and Hoppers

### ISSUE THREAD

**Issue by den-commits** [SiverDX/quality_food#35]
Hi there, this might be user error but it seems that pulling food out of a furnace automatically via a hopper causes the output to never get an assigned quality. Manually removing the food from the furnace appears to work as expected.

1.21.1 NeoForge
Quality Food 1.21.1 - 2.1.4

**Comment by SiverDX** [comment]
Fixed in the newest release

**Comment by den-commits** [comment]
Works perfectly and thanks for the crazy fast turnaround! (also the cooking changes are great)
