### ISSUE TITLE
support croptopia

### ISSUE THREAD

**Issue by krjencik** [SiverDX/quality_food#36]
Im using croptopia in my modpack. I would be really happy if there were quality items for this mod.

**Comment by SiverDX** [comment]
As long as the mod is using the proper tags it should already work
I tested it with some items in 1.21 and they were applicable to quality (incl. the drops from the trees)

**Comment by 27rogi** [comment]
Would it be possible to investigate the issue further? I'm using latest Croptopia and Quality Food mods on 1.20.1 version and got zero tiered **seeds** from bushes or by manually growing them with bone meal. 

Trees indeed give a tiered fruits, but their quality also lost when making saplings from them.
