### ISSUE TITLE
Freeze/crash on world creation

### ISSUE THREAD

**Issue by goldrat1** [SiverDX/quality_food#37]
Using a latest version of Quality Food on Forge 1.20.1 v47.3.10 with no other mods installed can occasionally cause the game to freeze indefinitely when creating a new world.
This definitely happens when generating Superflat worlds but I haven't had the opportunity to test if it happens during normal world creation.
Latest.log attached, had to force quit the game so no crash report was generated.

[latest.log](https://github.com/user-attachments/files/17713821/latest.log)

**Comment by SiverDX** [comment]
Can you check if it works with

[quality_food-1.20.1-2.1.0-all.zip](https://github.com/user-attachments/files/17714818/quality_food-1.20.1-2.1.0-all.zip)
