### ISSUE TITLE
higher quality crops cant be crafted into the corresponding quality seeds.

### ISSUE THREAD

**Issue by krjencik** [SiverDX/quality_food#38]
![2024-11-16_12 57 13](https://github.com/user-attachments/assets/3d79750b-fad6-4100-916b-5ba1eefcf5ea)

... but maybe thats intended?

**Comment by SiverDX** [comment]
There is a config for this - `retain_quality_recipes`
In there you can define recipes which should retain the quality

**Comment by SiverDX** [comment]
In the latest release (currently being uploaded) there is a config to retain the quality for recipes whose output is a seed
