### ISSUE TITLE
[suggest] Add a setting in config, you can choose whether to display the effect icon

### ISSUE THREAD

**Issue by QLNPLUS** [SiverDX/quality_food#39]
Because some mod new effects do not always display the icon correctly, for the sake of unity or for the sake of concise display, I think it is also a good choice not to display the icon

**Comment by SiverDX** [comment]
There already is a setting to disable the effect tooltips
I'm not sure if I want to start doing such granular configs

Are there any known problematic effect icons?

**Comment by QLNPLUS** [comment]
I see, it was written in tooltips so dont show the icon,these will show tooltips twice, and some food just no effect tooltips

**Comment by SiverDX** [comment]
I don't understand what you are trying to tell me there

If the config is enabled existing effect tooltips should be removed (and replaced with the custom ones from this mod)
If it is disabled no effect tooltips will be added / no existing ones will be removed

**Comment by SiverDX** [comment]
As mentioned above, there is a config to disable the custom tooltip logic for effects
