### ISSUE TITLE
[Suggestion] add quark right click compat

### ISSUE THREAD

**Issue by ianm1647** [SiverDX/quality_food#6]
title pretty much explains this, but quark right click compat would be absolutely amazing if you can add it, no rush on it, just seeing this in the future would be amazing

**Comment by ianm1647** [comment]
yeah thats exactly what it is

**Comment by SiverDX** [comment]
theoretically you can already achieve this using the config

https://github.com/VazkiiMods/Quark/blob/213658598ed9be4b78def54fa0fda4125f9dbcf8/src/main/java/vazkii/quark/content/tweaks/module/SimpleHarvestModule.java#L80-L88

i.e. `"minecraft:wheat[age=7,quality_food=3],minecraft:wheat[age=0,quality_food=3]"`
it would mean adding a lot of config entries
but it also means users can specify whether certain quality should be auto-replanted / quick-harvested or not etc.

not sure if i should bypass said config

**Comment by Lucky-56** [comment]
you could auto fill it if both mods are installed
